### ISSUE TITLE
Snowplow Page Pings send Double instead of Int as pp_miy and pp_mix

### ISSUE THREAD

**Issue by max-tgam** [snowplow-incubator/amphtml#10] opened 2020-06-03 16:06 UTC
In some cases Snowplow AMP PagePings send pp_miy and pp_mix values as Double instead of Int causing events to go into bad stream.

This is issue with `${scrollLeft}` and `${scrollTop}` not returning integer values in some cases (about 35% of cases).

## How do we reproduce the issue?

This requires you to visit a page on Android device and scroll around until you get Double value.
Example of a page can be found here:
https://www.news24.com/amp/news24/southafrica/news/cape-town-covid-19-tests-those-younger-than-55-and-without-comorbidity-may-no-longer-be-tested-20200602

## What browsers are affected?

Android Chrome (various versions)

## Which AMP version is affected?

It looks like it was always behaving like this.

**Comment by max-tgam** [comment] 2020-06-03 16:08
@colmsnowplow FYI. This looks like AMP bug specific to Android. Not sure how to address it. Should it be raised with AMP or should logic for Page Pings on Snowplow side be adjusted to accept double values?

**Comment by colmsnowplow** [comment] 2020-06-04 08:40
Thanks for reporting @max-tgam. 

I had this problem reported elsewhere but was unable to pin down the source, it's great to narrow it down to only on android. My hunch is that this is unexpected behaviour from the AMP platform, so I'll report that to them now that you have provided a way to repro. Appreciate it!

I have a workaround - there is a new trigger called 'ampPagePing' - this will send a new page ping event specifically to AMP ([docs](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/google-amp-tracker/google-amp-1-0-0-2/#page-pings)) - the schema for this event defines those fields as `number`. 

Technically, I think it should be an int, but because we have little control over the environment I decided to make it more permissive than that for now. 

Incidentally, I think it's preferable to use the ampPagePing trigger anyway - because the data you get from AMP pings is logically different to the JS tracker's ones, and so dealing with them differently is easier when they are a distinct event (although it is beginning to be a concern that the AMP tracking is proliferating new events and entities which makes things awkward too - something we're thinking about in the longer term).

If you swap to using `ampPagePing` trigger, I believe you'll no longer get these events going to bad rows.

**Comment by colmsnowplow** [comment] 2021-02-03 10:27
The root cause is now fixed on the AMP side: https://github.com/ampproject/amphtml/pull/28787

**Closed as completed by colmsnowplow** 2021-02-03 10:27 UTC
